d_model: 512
d_inner: 2048
n_layer: 12
n_head: 8
dropout: 0.1
max_grad_norm: 3

gpu_id: 2
train_id: wikifonia-0317
batch_size: 35
n_epoch: 100
init_lr: 0.0001
adam_beta1: 0.9
adam_beta2: 0.999

path_root: data
load_model: data/train/wikifonia-0317/epoch_55_params.pt